title: Emmanuel Ajuelos
logo: "/images/matronche.jpg?raw=true"
description: > 
  Computer science student at Sorbonne Université
  <br><br>
  I'm designing a more suitable website now that I have some free time - I hope that I'll be able to deploy it before classes start on september !
  <br><br>
  <a href="https://ajuelosemmanuel.github.io/followedcourses">Followed Courses</a>
  <br><br>
  <a href="https://ajuelosemmanuel.github.io/portfolio">My portfolio</a>
  <br><br>
  <a href="https://linkedin.com/in/ajuelosemmanuel" target="blank"><img align="center" src="https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/linkedin.svg" alt="ajuelosemmanuel" height="30" width="40" /></a>
  <a href="https://instagram.com/ajuelosemmanuel" target="blank"><img align="center" src="https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/instagram.svg" alt="ajuelosemmanuel" height="30" width="40" /></a>
  <br><br>
  <img align="center" src="https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/discord.svg" alt="Emmanuel#9864" height="30" width="40" /> Emmanuel#9864
theme: jekyll-theme-minimal
