title: Emmanuel Ajuelos
logo: "/images/matronche.jpg?raw=true"
description: > 
  Computer science student at Sorbonne Université
  <br><br>
  <a href="https://ajuelosemmanuel.github.io/followedcourses">Followed Courses</a>
  <br><br>
  <a href="https://linkedin.com/in/ajuelosemmanuel" target="blank"><img align="center" src="https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/linkedin.svg" alt="ajuelosemmanuel" height="30" width="40" /></a>
  
theme: jekyll-theme-minimal
